#!/usr/bin/env python3

def commands():
import sys

name = sys.argv[1]
year_of_birth = sys.argv[2]

print("Hi " + name + ", you are " + year_of_birth + " years old.")

print("Variable1 = " + name)
print("Variable2 = " + year_of_birth)

print("The script and varibles used are: " + str(sys.argv))
commands()

def helloWorld():
	print(‘Hello World’)


helloWorld()

